import { PatientType } from "../ui/PatientDataTable";

export const mockData: PatientType[] = [
  {
    id: "asdfa",
    isReceived: "Y",
    patientId: "testID",
    patientName: "jjunny",
    isMale: "Male",
    birthday: "1998-10-31",
    operationDate: "2025-04-05",
    institution: "SMC",
  },
  {
    id: "asdfa",
    isReceived: "Y",
    patientId: "testID",
    patientName: "jjunny",
    isMale: "Male",
    birthday: "1998-10-31",
    operationDate: "2025-04-05",
    institution: "SMC",
  },
  {
    id: "asdfa",
    isReceived: "Y",
    patientId: "testID",
    patientName: "jjunny",
    isMale: "Male",
    birthday: "1998-10-31",
    operationDate: "2025-04-05",
    institution: "SMC",
  },
  {
    id: "asdfa",
    isReceived: "Y",
    patientId: "testID",
    patientName: "jjunny",
    isMale: "Male",
    birthday: "1998-10-31",
    operationDate: "2025-04-05",
    institution: "SMC",
  },
  {
    id: "asdfa",
    isReceived: "Y",
    patientId: "testID",
    patientName: "jjunny",
    isMale: "Male",
    birthday: "1998-10-31",
    operationDate: "2025-04-05",
    institution: "SMC",
  },
  {
    id: "asdfa",
    isReceived: "Y",
    patientId: "testID",
    patientName: "jjunny",
    isMale: "Male",
    birthday: "1998-10-31",
    operationDate: "2025-04-05",
    institution: "SMC",
  },
  {
    id: "asdfa",
    isReceived: "Y",
    patientId: "testID",
    patientName: "jjunny",
    isMale: "Male",
    birthday: "1998-10-31",
    operationDate: "2025-04-05",
    institution: "SMC",
  },
  {
    id: "asdfa",
    isReceived: "Y",
    patientId: "testID",
    patientName: "jjunny",
    isMale: "Male",
    birthday: "1998-10-31",
    operationDate: "2025-04-05",
    institution: "SMC",
  },
  {
    id: "asdfa",
    isReceived: "Y",
    patientId: "testID",
    patientName: "jjunny",
    isMale: "Male",
    birthday: "1998-10-31",
    operationDate: "2025-04-05",
    institution: "SMC",
  },
  {
    id: "asdfa",
    isReceived: "Y",
    patientId: "testID",
    patientName: "jjunny",
    isMale: "Male",
    birthday: "1998-10-31",
    operationDate: "2025-04-05",
    institution: "SMC",
  },
  {
    id: "asdfa",
    isReceived: "Y",
    patientId: "testID",
    patientName: "jjunny",
    isMale: "Male",
    birthday: "1998-10-31",
    operationDate: "2025-04-05",
    institution: "SMC",
  },
  {
    id: "asdfa",
    isReceived: "Y",
    patientId: "testID",
    patientName: "jjunny",
    isMale: "Male",
    birthday: "1998-10-31",
    operationDate: "2025-04-05",
    institution: "SMC",
  },
  {
    id: "asdfa",
    isReceived: "Y",
    patientId: "testID",
    patientName: "jjunny",
    isMale: "Male",
    birthday: "1998-10-31",
    operationDate: "2025-04-05",
    institution: "SMC",
  },
  {
    id: "asdfa",
    isReceived: "Y",
    patientId: "testID",
    patientName: "jjunny",
    isMale: "Male",
    birthday: "1998-10-31",
    operationDate: "2025-04-05",
    institution: "SMC",
  },
  {
    id: "asdfa",
    isReceived: "Y",
    patientId: "testID",
    patientName: "jjunny",
    isMale: "Male",
    birthday: "1998-10-31",
    operationDate: "2025-04-05",
    institution: "SMC",
  },
];
